### ISSUE TITLE
Create server

### ISSUE THREAD

**Issue by kerelape** [kerelape/gophkeeper0#2]

**Comment by 0pdd** [comment]
@kerelape the puzzle [#5](https://github.com/kerelape/gophkeeper/issues/5) is still not solved.

**Comment by 0pdd** [comment]
@kerelape 5 puzzles [#10](https://github.com/kerelape/gophkeeper/issues/10), [#5](https://github.com/kerelape/gophkeeper/issues/5), [#7](https://github.com/kerelape/gophkeeper/issues/7), [#8](https://github.com/kerelape/gophkeeper/issues/8), [#9](https://github.com/kerelape/gophkeeper/issues/9) are still not solved.

**Comment by 0pdd** [comment]
@kerelape 4 puzzles [#10](https://github.com/kerelape/gophkeeper/issues/10), [#7](https://github.com/kerelape/gophkeeper/issues/7), [#8](https://github.com/kerelape/gophkeeper/issues/8), [#9](https://github.com/kerelape/gophkeeper/issues/9) are still not solved; solved: [#5](https://github.com/kerelape/gophkeeper/issues/5).

**Comment by 0pdd** [comment]
@kerelape the puzzle [#7](https://github.com/kerelape/gophkeeper/issues/7) is still not solved; solved: [#10](https://github.com/kerelape/gophkeeper/issues/10), [#5](https://github.com/kerelape/gophkeeper/issues/5), [#8](https://github.com/kerelape/gophkeeper/issues/8), [#9](https://github.com/kerelape/gophkeeper/issues/9).

**Comment by 0pdd** [comment]
@kerelape 5 puzzles [#15](https://github.com/kerelape/gophkeeper/issues/15), [#16](https://github.com/kerelape/gophkeeper/issues/16), [#17](https://github.com/kerelape/gophkeeper/issues/17), [#18](https://github.com/kerelape/gophkeeper/issues/18), [#19](https://github.com/kerelape/gophkeeper/issues/19) are still not solved; solved: [#10](https://github.com/kerelape/gophkeeper/issues/10), [#5](https://github.com/kerelape/gophkeeper/issues/5), [#7](https://github.com/kerelape/gophkeeper/issues/7), [#8](https://github.com/kerelape/gophkeeper/issues/8), [#9](https://github.com/kerelape/gophkeeper/issues/9).

**Comment by 0pdd** [comment]
@kerelape 5 puzzles [#15](https://github.com/kerelape/gophkeeper/issues/15), [#17](https://github.com/kerelape/gophkeeper/issues/17), [#18](https://github.com/kerelape/gophkeeper/issues/18), [#19](https://github.com/kerelape/gophkeeper/issues/19), [#21](https://github.com/kerelape/gophkeeper/issues/21) are still not solved; solved: [#10](https://github.com/kerelape/gophkeeper/issues/10), [#16](https://github.com/kerelape/gophkeeper/issues/16), [#5](https://github.com/kerelape/gophkeeper/issues/5), [#7](https://github.com/kerelape/gophkeeper/issues/7), [#8](https://github.com/kerelape/gophkeeper/issues/8), [#9](https://github.com/kerelape/gophkeeper/issues/9).

**Comment by 0pdd** [comment]
@kerelape 4 puzzles [#15](https://github.com/kerelape/gophkeeper/issues/15), [#17](https://github.com/kerelape/gophkeeper/issues/17), [#18](https://github.com/kerelape/gophkeeper/issues/18), [#19](https://github.com/kerelape/gophkeeper/issues/19) are still not solved; solved: [#10](https://github.com/kerelape/gophkeeper/issues/10), [#16](https://github.com/kerelape/gophkeeper/issues/16), [#21](https://github.com/kerelape/gophkeeper/issues/21), [#5](https://github.com/kerelape/gophkeeper/issues/5), [#7](https://github.com/kerelape/gophkeeper/issues/7), [#8](https://github.com/kerelape/gophkeeper/issues/8), [#9](https://github.com/kerelape/gophkeeper/issues/9).

**Comment by 0pdd** [comment]
@kerelape 3 puzzles [#17](https://github.com/kerelape/gophkeeper/issues/17), [#18](https://github.com/kerelape/gophkeeper/issues/18), [#19](https://github.com/kerelape/gophkeeper/issues/19) are still not solved; solved: [#10](https://github.com/kerelape/gophkeeper/issues/10), [#15](https://github.com/kerelape/gophkeeper/issues/15), [#16](https://github.com/kerelape/gophkeeper/issues/16), [#21](https://github.com/kerelape/gophkeeper/issues/21), [#5](https://github.com/kerelape/gophkeeper/issues/5), [#7](https://github.com/kerelape/gophkeeper/issues/7), [#8](https://github.com/kerelape/gophkeeper/issues/8), [#9](https://github.com/kerelape/gophkeeper/issues/9).

**Comment by 0pdd** [comment]
@kerelape the puzzle [#18](https://github.com/kerelape/gophkeeper/issues/18) is still not solved; solved: [#10](https://github.com/kerelape/gophkeeper/issues/10), [#15](https://github.com/kerelape/gophkeeper/issues/15), [#16](https://github.com/kerelape/gophkeeper/issues/16), [#17](https://github.com/kerelape/gophkeeper/issues/17), [#19](https://github.com/kerelape/gophkeeper/issues/19), [#21](https://github.com/kerelape/gophkeeper/issues/21), [#5](https://github.com/kerelape/gophkeeper/issues/5), [#7](https://github.com/kerelape/gophkeeper/issues/7), [#8](https://github.com/kerelape/gophkeeper/issues/8), [#9](https://github.com/kerelape/gophkeeper/issues/9).

**Comment by 0pdd** [comment]
@kerelape all 11 puzzles are solved here: [#10](https://github.com/kerelape/gophkeeper/issues/10), [#15](https://github.com/kerelape/gophkeeper/issues/15), [#16](https://github.com/kerelape/gophkeeper/issues/16), [#17](https://github.com/kerelape/gophkeeper/issues/17), [#18](https://github.com/kerelape/gophkeeper/issues/18), [#19](https://github.com/kerelape/gophkeeper/issues/19), [#21](https://github.com/kerelape/gophkeeper/issues/21), [#5](https://github.com/kerelape/gophkeeper/issues/5), [#7](https://github.com/kerelape/gophkeeper/issues/7), [#8](https://github.com/kerelape/gophkeeper/issues/8), [#9](https://github.com/kerelape/gophkeeper/issues/9).
