### ISSUE TITLE
Create interface

### ISSUE THREAD

**Issue by kerelape** [kerelape/gophkeeper0#28]

**Comment by 0pdd** [comment]
@kerelape 2 puzzles [#30](https://github.com/kerelape/gophkeeper/issues/30), [#31](https://github.com/kerelape/gophkeeper/issues/31) are still not solved.

**Comment by 0pdd** [comment]
@kerelape 3 puzzles [#30](https://github.com/kerelape/gophkeeper/issues/30), [#31](https://github.com/kerelape/gophkeeper/issues/31), [#33](https://github.com/kerelape/gophkeeper/issues/33) are still not solved.

**Comment by 0pdd** [comment]
@kerelape 2 puzzles [#30](https://github.com/kerelape/gophkeeper/issues/30), [#31](https://github.com/kerelape/gophkeeper/issues/31) are still not solved; solved: [#33](https://github.com/kerelape/gophkeeper/issues/33).

**Comment by 0pdd** [comment]
@kerelape the puzzle [#31](https://github.com/kerelape/gophkeeper/issues/31) is still not solved; solved: [#30](https://github.com/kerelape/gophkeeper/issues/30), [#33](https://github.com/kerelape/gophkeeper/issues/33).

**Comment by 0pdd** [comment]
@kerelape 6 puzzles [#38](https://github.com/kerelape/gophkeeper/issues/38), [#39](https://github.com/kerelape/gophkeeper/issues/39), [#40](https://github.com/kerelape/gophkeeper/issues/40), [#41](https://github.com/kerelape/gophkeeper/issues/41), [#42](https://github.com/kerelape/gophkeeper/issues/42), [#43](https://github.com/kerelape/gophkeeper/issues/43) are still not solved; solved: [#30](https://github.com/kerelape/gophkeeper/issues/30), [#31](https://github.com/kerelape/gophkeeper/issues/31), [#33](https://github.com/kerelape/gophkeeper/issues/33).

**Comment by 0pdd** [comment]
@kerelape 4 puzzles [#40](https://github.com/kerelape/gophkeeper/issues/40), [#41](https://github.com/kerelape/gophkeeper/issues/41), [#42](https://github.com/kerelape/gophkeeper/issues/42), [#43](https://github.com/kerelape/gophkeeper/issues/43) are still not solved; solved: [#30](https://github.com/kerelape/gophkeeper/issues/30), [#31](https://github.com/kerelape/gophkeeper/issues/31), [#33](https://github.com/kerelape/gophkeeper/issues/33), [#38](https://github.com/kerelape/gophkeeper/issues/38), [#39](https://github.com/kerelape/gophkeeper/issues/39).

**Comment by 0pdd** [comment]
@kerelape 3 puzzles [#42](https://github.com/kerelape/gophkeeper/issues/42), [#43](https://github.com/kerelape/gophkeeper/issues/43), [#46](https://github.com/kerelape/gophkeeper/issues/46) are still not solved; solved: [#30](https://github.com/kerelape/gophkeeper/issues/30), [#31](https://github.com/kerelape/gophkeeper/issues/31), [#33](https://github.com/kerelape/gophkeeper/issues/33), [#38](https://github.com/kerelape/gophkeeper/issues/38), [#39](https://github.com/kerelape/gophkeeper/issues/39), [#40](https://github.com/kerelape/gophkeeper/issues/40), [#41](https://github.com/kerelape/gophkeeper/issues/41).

**Comment by 0pdd** [comment]
@kerelape 2 puzzles [#42](https://github.com/kerelape/gophkeeper/issues/42), [#43](https://github.com/kerelape/gophkeeper/issues/43) are still not solved; solved: [#30](https://github.com/kerelape/gophkeeper/issues/30), [#31](https://github.com/kerelape/gophkeeper/issues/31), [#33](https://github.com/kerelape/gophkeeper/issues/33), [#38](https://github.com/kerelape/gophkeeper/issues/38), [#39](https://github.com/kerelape/gophkeeper/issues/39), [#40](https://github.com/kerelape/gophkeeper/issues/40), [#41](https://github.com/kerelape/gophkeeper/issues/41), [#46](https://github.com/kerelape/gophkeeper/issues/46).

**Comment by 0pdd** [comment]
@kerelape the puzzle [#42](https://github.com/kerelape/gophkeeper/issues/42) is still not solved; solved: [#30](https://github.com/kerelape/gophkeeper/issues/30), [#31](https://github.com/kerelape/gophkeeper/issues/31), [#33](https://github.com/kerelape/gophkeeper/issues/33), [#38](https://github.com/kerelape/gophkeeper/issues/38), [#39](https://github.com/kerelape/gophkeeper/issues/39), [#40](https://github.com/kerelape/gophkeeper/issues/40), [#41](https://github.com/kerelape/gophkeeper/issues/41), [#43](https://github.com/kerelape/gophkeeper/issues/43), [#46](https://github.com/kerelape/gophkeeper/issues/46).

**Comment by 0pdd** [comment]
@kerelape all 10 puzzles are solved here: [#30](https://github.com/kerelape/gophkeeper/issues/30), [#31](https://github.com/kerelape/gophkeeper/issues/31), [#33](https://github.com/kerelape/gophkeeper/issues/33), [#38](https://github.com/kerelape/gophkeeper/issues/38), [#39](https://github.com/kerelape/gophkeeper/issues/39), [#40](https://github.com/kerelape/gophkeeper/issues/40), [#41](https://github.com/kerelape/gophkeeper/issues/41), [#42](https://github.com/kerelape/gophkeeper/issues/42), [#43](https://github.com/kerelape/gophkeeper/issues/43), [#46](https://github.com/kerelape/gophkeeper/issues/46).
