### ISSUE TITLE
Create CLI client

### ISSUE THREAD

**Issue by kerelape** [kerelape/gophkeeper0#3]

**Comment by kerelape** [comment]
depends on: #28

**Comment by 0pdd** [comment]
@kerelape the puzzle [#54](https://github.com/kerelape/gophkeeper/issues/54) is still not solved.

**Comment by 0pdd** [comment]
@kerelape the puzzle [#56](https://github.com/kerelape/gophkeeper/issues/56) is still not solved; solved: [#54](https://github.com/kerelape/gophkeeper/issues/54).

**Comment by 0pdd** [comment]
@kerelape 11 puzzles [#57](https://github.com/kerelape/gophkeeper/issues/57), [#58](https://github.com/kerelape/gophkeeper/issues/58), [#59](https://github.com/kerelape/gophkeeper/issues/59), [#60](https://github.com/kerelape/gophkeeper/issues/60), [#61](https://github.com/kerelape/gophkeeper/issues/61), [#62](https://github.com/kerelape/gophkeeper/issues/62), [#63](https://github.com/kerelape/gophkeeper/issues/63), [#64](https://github.com/kerelape/gophkeeper/issues/64), [#65](https://github.com/kerelape/gophkeeper/issues/65), [#66](https://github.com/kerelape/gophkeeper/issues/66), [#67](https://github.com/kerelape/gophkeeper/issues/67) are still not solved; solved: [#54](https://github.com/kerelape/gophkeeper/issues/54), [#56](https://github.com/kerelape/gophkeeper/issues/56).

**Comment by 0pdd** [comment]
@kerelape 10 puzzles [#58](https://github.com/kerelape/gophkeeper/issues/58), [#59](https://github.com/kerelape/gophkeeper/issues/59), [#60](https://github.com/kerelape/gophkeeper/issues/60), [#61](https://github.com/kerelape/gophkeeper/issues/61), [#62](https://github.com/kerelape/gophkeeper/issues/62), [#63](https://github.com/kerelape/gophkeeper/issues/63), [#64](https://github.com/kerelape/gophkeeper/issues/64), [#65](https://github.com/kerelape/gophkeeper/issues/65), [#66](https://github.com/kerelape/gophkeeper/issues/66), [#67](https://github.com/kerelape/gophkeeper/issues/67) are still not solved; solved: [#54](https://github.com/kerelape/gophkeeper/issues/54), [#56](https://github.com/kerelape/gophkeeper/issues/56), [#57](https://github.com/kerelape/gophkeeper/issues/57).

**Comment by 0pdd** [comment]
@kerelape 8 puzzles [#60](https://github.com/kerelape/gophkeeper/issues/60), [#61](https://github.com/kerelape/gophkeeper/issues/61), [#62](https://github.com/kerelape/gophkeeper/issues/62), [#63](https://github.com/kerelape/gophkeeper/issues/63), [#64](https://github.com/kerelape/gophkeeper/issues/64), [#65](https://github.com/kerelape/gophkeeper/issues/65), [#66](https://github.com/kerelape/gophkeeper/issues/66), [#67](https://github.com/kerelape/gophkeeper/issues/67) are still not solved; solved: [#54](https://github.com/kerelape/gophkeeper/issues/54), [#56](https://github.com/kerelape/gophkeeper/issues/56), [#57](https://github.com/kerelape/gophkeeper/issues/57), [#58](https://github.com/kerelape/gophkeeper/issues/58), [#59](https://github.com/kerelape/gophkeeper/issues/59).

**Comment by 0pdd** [comment]
@kerelape 7 puzzles [#61](https://github.com/kerelape/gophkeeper/issues/61), [#62](https://github.com/kerelape/gophkeeper/issues/62), [#63](https://github.com/kerelape/gophkeeper/issues/63), [#64](https://github.com/kerelape/gophkeeper/issues/64), [#65](https://github.com/kerelape/gophkeeper/issues/65), [#66](https://github.com/kerelape/gophkeeper/issues/66), [#67](https://github.com/kerelape/gophkeeper/issues/67) are still not solved; solved: [#54](https://github.com/kerelape/gophkeeper/issues/54), [#56](https://github.com/kerelape/gophkeeper/issues/56), [#57](https://github.com/kerelape/gophkeeper/issues/57), [#58](https://github.com/kerelape/gophkeeper/issues/58), [#59](https://github.com/kerelape/gophkeeper/issues/59), [#60](https://github.com/kerelape/gophkeeper/issues/60).

**Comment by 0pdd** [comment]
@kerelape 6 puzzles [#61](https://github.com/kerelape/gophkeeper/issues/61), [#62](https://github.com/kerelape/gophkeeper/issues/62), [#63](https://github.com/kerelape/gophkeeper/issues/63), [#65](https://github.com/kerelape/gophkeeper/issues/65), [#66](https://github.com/kerelape/gophkeeper/issues/66), [#67](https://github.com/kerelape/gophkeeper/issues/67) are still not solved; solved: [#54](https://github.com/kerelape/gophkeeper/issues/54), [#56](https://github.com/kerelape/gophkeeper/issues/56), [#57](https://github.com/kerelape/gophkeeper/issues/57), [#58](https://github.com/kerelape/gophkeeper/issues/58), [#59](https://github.com/kerelape/gophkeeper/issues/59), [#60](https://github.com/kerelape/gophkeeper/issues/60), [#64](https://github.com/kerelape/gophkeeper/issues/64).

**Comment by 0pdd** [comment]
@kerelape 4 puzzles [#61](https://github.com/kerelape/gophkeeper/issues/61), [#62](https://github.com/kerelape/gophkeeper/issues/62), [#65](https://github.com/kerelape/gophkeeper/issues/65), [#66](https://github.com/kerelape/gophkeeper/issues/66) are still not solved; solved: [#54](https://github.com/kerelape/gophkeeper/issues/54), [#56](https://github.com/kerelape/gophkeeper/issues/56), [#57](https://github.com/kerelape/gophkeeper/issues/57), [#58](https://github.com/kerelape/gophkeeper/issues/58), [#59](https://github.com/kerelape/gophkeeper/issues/59), [#60](https://github.com/kerelape/gophkeeper/issues/60), [#63](https://github.com/kerelape/gophkeeper/issues/63), [#64](https://github.com/kerelape/gophkeeper/issues/64), [#67](https://github.com/kerelape/gophkeeper/issues/67).

**Comment by 0pdd** [comment]
@kerelape 2 puzzles [#62](https://github.com/kerelape/gophkeeper/issues/62), [#66](https://github.com/kerelape/gophkeeper/issues/66) are still not solved; solved: [#54](https://github.com/kerelape/gophkeeper/issues/54), [#56](https://github.com/kerelape/gophkeeper/issues/56), [#57](https://github.com/kerelape/gophkeeper/issues/57), [#58](https://github.com/kerelape/gophkeeper/issues/58), [#59](https://github.com/kerelape/gophkeeper/issues/59), [#60](https://github.com/kerelape/gophkeeper/issues/60), [#61](https://github.com/kerelape/gophkeeper/issues/61), [#63](https://github.com/kerelape/gophkeeper/issues/63), [#64](https://github.com/kerelape/gophkeeper/issues/64), [#65](https://github.com/kerelape/gophkeeper/issues/65), [#67](https://github.com/kerelape/gophkeeper/issues/67).

**Comment by 0pdd** [comment]
@kerelape all 13 puzzles are solved here: [#54](https://github.com/kerelape/gophkeeper/issues/54), [#56](https://github.com/kerelape/gophkeeper/issues/56), [#57](https://github.com/kerelape/gophkeeper/issues/57), [#58](https://github.com/kerelape/gophkeeper/issues/58), [#59](https://github.com/kerelape/gophkeeper/issues/59), [#60](https://github.com/kerelape/gophkeeper/issues/60), [#61](https://github.com/kerelape/gophkeeper/issues/61), [#62](https://github.com/kerelape/gophkeeper/issues/62), [#63](https://github.com/kerelape/gophkeeper/issues/63), [#64](https://github.com/kerelape/gophkeeper/issues/64), [#65](https://github.com/kerelape/gophkeeper/issues/65), [#66](https://github.com/kerelape/gophkeeper/issues/66), [#67](https://github.com/kerelape/gophkeeper/issues/67).
