### ISSUE TITLE
Implement list & delete entries

### ISSUE THREAD

**Issue by kerelape** [kerelape/gophkeeper0#32]

**Comment by 0pdd** [comment]
@kerelape 2 puzzles [#49](https://github.com/kerelape/gophkeeper/issues/49), [#50](https://github.com/kerelape/gophkeeper/issues/50) are still not solved.

**Comment by 0pdd** [comment]
@kerelape the puzzle [#50](https://github.com/kerelape/gophkeeper/issues/50) is still not solved; solved: [#49](https://github.com/kerelape/gophkeeper/issues/49).

**Comment by 0pdd** [comment]
@kerelape all 2 puzzles are solved here: [#49](https://github.com/kerelape/gophkeeper/issues/49), [#50](https://github.com/kerelape/gophkeeper/issues/50).
